---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aap-monitoring

resources:
  - ../../../common/base/rbac

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: aap-monitoring
      - op: replace
        path: /metadata/name
        value: cluster-monitoring-view-aap
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: cluster-monitoring-view
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: aap-monitoring
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: auth-delegator-aap-grafana
  - patch: |-
      - op: add
        path: /subjects/0/namespace
        value: aap-monitoring
    target:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: grafana-proxy
